# Generated by Django 4.1.3 on 2022-12-26 16:42

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                #('category',models.ForeignKey(Category,on_delete=models.CASCADE,default=1)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
